### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by AlexKovalevych** [andrewtimberlake/mailroom#1]
iex(2)> {:ok, client} = POP3.connect("imap.mail.ru", username, password, port: 993, ssl: true)
** (CaseClauseError) no case clause matching: "* OK Welcome"
    (mailroom) lib/mailroom/pop3.ex:231: Mailroom.POP3.recv/1
    (mailroom) lib/mailroom/pop3.ex:178: Mailroom.POP3.login/3
    (mailroom) lib/mailroom/pop3.ex:41: Mailroom.POP3.connect/4

**Comment by AlexKovalevych** [comment]
Sorry, realised i should use pop instead of imap )

**Comment by andrewtimberlake** [comment]
@AlexKovalevych Thanks for trying this out, I’d love some feedback on how it’s going.
There is IMAP support in Mailroom, I just haven’t documented anything yet.

**Comment by AlexKovalevych** [comment]
@andrewtimberlake Thank you for this library, its exactly what i was looking for, but can you give me an example how i cant get unseen emails and add unseen flag to an existing email?

**Comment by andrewtimberlake** [comment]
@AlexKovalevych You can now use search
Search takes a string search query for now. I’ll work on a query DSL in future.

``` elixir
{:ok, client} = IMAP.connect("imap.mail.ru", username, password, port: 995, ssl: true)
client
|> IMAP.select(:inbox)
|> IMAP.search("UNSEEN", :envelope, fn({msg_id, _envelope}) ->
  IMAP.remove_flags(client, msg_id, :seen) # No unseen flag, just /Seen which needs to be removed
end)
|> IMAP.expunge
|> IMAP.logout
```

**Comment by AlexKovalevych** [comment]
@andrewtimberlake Awesome, thanks!
